=== aodn/aatams/resources/vue_integration/ulfx.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://vemco.com/vue"
           xmlns:v="http://vemco.com/vue">

    <xs:element name="ulfx">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">

                <xs:element name="definitions">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="deviceModel" type="v:deviceModel" />
                            <xs:element name="codeSpace" type="v:codeSpace" />
                            <xs:element name="recorder" type="v:recorder" />
                            <xs:element name="measurementUnit" type="v:measurementUnit" />
                            <xs:element name="transmitter" type="v:transmitter" >
                            
                                <!--  Ensure that sensor txr attribute is same as parent transmitter ID. -->
                                <xs:key name="sensorTransmitterKey">
                                    <xs:selector xpath="."/>
                                    <xs:field xpath="@id"/>
                                </xs:key>
                                <xs:keyref name="sensorTransmitterForeignKey" refer="v:sensorTransmitterKey">
                                    <xs:selector xpath="./sensor"/>
                                    <xs:field xpath="@txr"/>
                                </xs:keyref>
                            
                                <!--  Ensure that sensor ID is unique within a transmitter. -->
                                <xs:unique name="sensorIdUnique">
                                    <xs:selector xpath="./sensor"/>
                                    <xs:field xpath="@id"/>
                                </xs:unique>
                              
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>

                <xs:element name="context">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="recorderFW" type="v:recorderFW" />
                            <xs:element name="offload" type="v:offload" />
                            <xs:element name="contextSet" type="v:contextSet" />
                        </xs:choice>
                    </xs:complexType>
                </xs:element>

                <xs:element name="records">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="detection" type="v:detection" >
                            
                                <!--  Ensure that sample txr attribute is same as parent (detection) txr FK. -->
						        <xs:key name="detectionTransmitterKey">
						            <xs:selector xpath="."/>
						            <xs:field xpath="@txr"/>
						        </xs:key>
						        
						        <xs:keyref name="sampleDetectionTransmitterForeignKey" refer="v:detectionTransmitterKey">
						            <xs:selector xpath="./sample"/>
						            <xs:field xpath="@txr"/>
						        </xs:keyref>
						        
						        <!--  Ensure that sensor ID is unique within a detection. -->
						        <xs:key name="sampleKey">
                                    <xs:selector xpath="./sample"/>
                                    <xs:field xpath="@sensor"/>
						        </xs:key>
						        
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>

            </xs:choice>
        </xs:complexType>


        <!-- Key Definitions -->

        <xs:key name="deviceModelKey">
            <xs:selector xpath="./definitions/deviceModel"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="measurementUnitKey">
            <xs:selector xpath="./definitions/measurementUnit"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="codeSpaceKey">
            <xs:selector xpath="./definitions/codeSpace"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="recorderKey">
            <xs:selector xpath="./definitions/recorder" />
            <xs:field xpath="@id" />
        </xs:key>

        <xs:key name="transmitterKey">
            <xs:selector xpath="./definitions/transmitter"/>
            <xs:field xpath="@id"/>
        </xs:key>

         <xs:key name="sensorKey">
            <xs:selector xpath="./definitions/transmitter/sensor"/>
            <xs:field xpath="@id"/>
            <xs:field xpath="@txr"/>
        </xs:key>

        <xs:key name="recorderFWKey">
            <xs:selector xpath="./context/recorderFW"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="offloadContextKey">
            <xs:selector xpath="./context/offload"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="offloadSetKey">
            <xs:selector xpath="./context/contextSet"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <!-- Uniqueness Constraints -->

        <xs:unique name="recorderModelUnique">
            <xs:selector xpath="./definitions/recorder"/>
            <xs:field xpath="@model"/>
            <xs:field xpath="@serial"/>
        </xs:unique>

        <xs:unique name="offloadContextUnique">
            <xs:selector xpath="./context/offload" />
            <xs:field xpath="@uuid" />
        </xs:unique>

        <xs:unique name="detectionRecordUnique">
            <xs:selector xpath="./records/detection"/>
            <xs:field xpath="@time"/>
            <xs:field xpath="@txr"/>
            <xs:field xpath="@rxr"/>
        </xs:unique>


        <!-- Foreign Key Definitions -->

        <xs:keyref name="transmitterCodeSpaceForeignKey" refer="v:codeSpaceKey">
            <xs:selector xpath="./definitions/transmitter"/>
            <xs:field xpath="@codeSpace"/>
        </xs:keyref>

        <xs:keyref name="recorderModelForeignKey" refer="v:deviceModelKey">
            <xs:selector xpath="./definitions/recorder"/>
            <xs:field xpath="@model"/>
        </xs:keyref>

        <xs:keyref name="contextSetRecordingContextForeignKey" refer="v:recorderFWKey">
            <xs:selector xpath="./context/contextSet"/>
            <xs:field xpath="@recorderFW"/>
        </xs:keyref>

        <xs:keyref name="contextSetOffloadContextForeignKey" refer="v:offloadContextKey">
            <xs:selector xpath="./context/contextSet"/>
            <xs:field xpath="@offload"/>
        </xs:keyref>

        <xs:keyref name="detectionTransmitterForeignKey" refer="v:transmitterKey">
            <xs:selector xpath="./records/detection"/>
            <xs:field xpath="@txr"/>
        </xs:keyref>
        
        <xs:keyref name="detectionSensorForeignKey" refer="v:sensorKey">
            <xs:selector xpath="./records/detection/sample"/>
            <xs:field xpath="@sensor"/>
            <xs:field xpath="@txr"/>
        </xs:keyref>
        
        <xs:keyref name="detectionRecorderForeignKey" refer="v:recorderKey">
            <xs:selector xpath="./records/detection"/>
            <xs:field xpath="@rxr"/>
        </xs:keyref>

        <xs:keyref name="detectionContextForeignKey" refer="v:offloadSetKey">
            <xs:selector xpath="./records/detection"/>
            <xs:field xpath="@ctx"/>
        </xs:keyref>
    </xs:element>


    <!--  Type Definitions. -->

    <xs:simpleType name="uuid">
        <xs:restriction base="xs:hexBinary">
            <xs:length value="16"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="modelCode">
        <xs:restriction base="xs:hexBinary">
            <xs:length value="2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="mcc">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A"/>
            <xs:enumeration value="E"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="version">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,2}[.]\d{1,2}[.]\d{1,6}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="measurementUnit">
        <xs:attribute name="id" type="xs:int"/>
        <xs:attribute name="dimension" type="xs:int"/>
        <xs:attribute name="displayUnit" type="xs:string"/>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="displayDimension" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="deviceModel">
        <xs:attribute name="id" type="xs:int"/>
        <xs:attribute name="model" type="v:modelCode"/>
        <xs:attribute name="class" type="xs:int"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="description" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="recorder">
        <xs:attribute name="id" type="xs:int"/>
        <xs:attribute name="model" type="xs:int"/>
        <xs:attribute name="serial" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="codeSpace">
        <xs:attribute name="id" type="xs:int"/>
        <xs:attribute name="codingId" type="xs:int"/>
        <xs:attribute name="mcc" type="v:mcc" use="required"/>
        <xs:attribute name="freq" type="xs:int" use="required"/>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="displayType" type="xs:string"/>
        <xs:attribute name="sensorBits" type="xs:int" use="optional"/>
    </xs:complexType>

    <xs:complexType name="sensor">
        <xs:attribute name="id" type="xs:int"/>
        <xs:attribute name="txr" type="xs:int"/>
        <xs:attribute name="slope" type="xs:decimal" use="optional"/>
        <xs:attribute name="intercept" type="xs:decimal" use="optional"/>
        <xs:attribute name="unit" type="xs:int" use="optional"/>
    </xs:complexType>

    <xs:complexType name="transmitter">
        <xs:sequence>
            <xs:element name="sensor" type="v:sensor" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
        <xs:attribute name="tagId" type="xs:int"/>
        <xs:attribute name="codeSpace" type="xs:int"/>
        <xs:attribute name="model" type="v:modelCode" use="optional"/>
        <xs:attribute name="name" type="xs:string" use="optional"/>
        <xs:attribute name="serial" type="xs:int" use="optional"/>
    </xs:complexType>
    
    <xs:complexType name="recorderFW">
        <xs:attribute name="id" type="xs:int"/>
        <xs:attribute name="version" type="v:version"/>
        <xs:attribute name="displayVersion" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="offload">
        <xs:attribute name="id" type="xs:int"/>
        <xs:attribute name="time" type="xs:dateTime"/>
        <xs:attribute name="uuid" type="v:uuid"/>
        <xs:attribute name="appName" type="xs:string" use="optional"/>
        <xs:attribute name="appVersion" type="v:version" use="optional"/>
        <xs:attribute name="pluginName" type="xs:string" use="optional"/>
        <xs:attribute name="pluginVersion" type="v:version" use="optional"/>
    </xs:complexType>

    <xs:complexType name="contextSet">
        <xs:attribute name="id" type="xs:int"/>
        <xs:attribute name="recorderFW" type="xs:int"/>
        <xs:attribute name="offload" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="detection">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="sample" type="v:sample" />
        </xs:choice>
        <xs:attribute name="time" type="xs:dateTime"/>
        <xs:attribute name="txr" type="xs:int"/>
        <xs:attribute name="rxr" type="xs:int"/>
        <xs:attribute name="ctx" type="xs:int"/>
        <xs:attribute name="cooked" type="xs:boolean" use="optional"/>
        <xs:attribute name="correctedTime" type="xs:dateTime" use="optional"/>
    </xs:complexType>

    <xs:complexType name="sample">
        <xs:attribute name="sensor" type="xs:int" />
        <xs:attribute name="txr" type="xs:int"/>
        <xs:attribute name="adc" type="xs:decimal" use="optional"/>
        <xs:attribute name="val" type="xs:decimal" use="optional"/>
    </xs:complexType>
</xs:schema>

=== aodn/aatams/resources/vue_integration/valid_example.xml
<?xml version="1.0" encoding="UTF-8"?>


<v:ulfx xmlns:v="http://vemco.com/vue"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://vemco.com/vue ulfx.xsd">


    <!-- Global Definitions (hardcoded in VUE) -->

    <definitions>
        <deviceModel id="1" model="0202" class="1" name="VR2W" description="VR2W Acoustic receiver (69 kHz)" />
        <deviceModel id="2" model="0203" class="1" name="VR2W81" description="VR2W Acoustic receiver (81 kHz)" />
        <deviceModel id="3" model="0204" class="1" name="VR2W180" description="VR2W Acoustic receiver (180 kHz)" />

        <measurementUnit id="1" dimension="101" displayUnit="m" displayName="metres" displayDimension="distance" />
        <measurementUnit id="2" dimension="102" displayUnit="Pa" displayName="pascals" displayDimension="pressure" />
        <measurementUnit id="5" dimension="0" displayUnit="ADC" displayName="ADC sample" displayDimension="" />
    </definitions>


    <!-- Data Collection Context (from VRL header(s)) -->

    <definitions>
        <recorder id="1" model="1" serial="12345" />
    </definitions>

    <context>
        <recorderFW id="1" version="1.2.3" displayVersion="1.2.3 Alpha Test Build" />
        <offload
            id="1"
            time="2012-06-12T12:34:56.000"
            uuid="550e8400e29b41d4a716446655440000"
            appName="VUE"
            appVersion="1.2.3"
            pluginName="VR2W"
            pluginVersion="4.5.6"
        />
        <contextSet id="1" recorderFW="1" offload="1"/>
    </context>


    <!-- Log Data (from ULF blocks) -->

    <definitions>
        <codeSpace id="1" codingId="1303" mcc="A" freq="69000" displayName="A69-1303" displayType="Coded Pinger"/>
        <codeSpace id="2" codingId="1105" mcc="A" freq="69000" displayName="A69-1105" displayType="Coded Sensor" sensorBits="8"/>
        <codeSpace id="3" codingId="201" mcc="A" freq="69000" displayName="A69-201" displayType="Continuous Dual Sensor"/>

        <transmitter id="1" codeSpace="1" tagId="456" />

        <transmitter id="2" codeSpace="2" tagId="123">
            <sensor id="1" unit="5" slope="5.6" intercept="7.8"/>
            
            <!--  Invalid - id not unique. -->
            <sensor id="1" unit="5" slope="5.6" intercept="7.8"/>
        </transmitter>

        <transmitter id="3" codeSpace="2" tagId="123">
            <sensor id="1" unit="2" />
        </transmitter>

        <transmitter id="4" codeSpace="3">
            <sensor id="1" slope="1.1" intercept="2.2" unit="1" />
            <sensor id="2" slope="3.3" intercept="4.4" unit="2" />
        </transmitter>
    </definitions>

    <records>
        <detection time="2012-06-13T12:33:56.000-04:00" txr="1" rxr="1" ctx="1" />
        <detection time="2012-06-13T12:34:56.000" txr="1" rxr="1" ctx="1" />
        <detection time="2012-06-13T12:35:56.000" txr="2" rxr="1" ctx="1">
            <sample sensor="1" adc="123"/>
            
            <!-- Invalid - sensor 2 doesn't exist for this txr 2. -->
            <sample sensor="2" adc="123"/>
            
        </detection>
        <detection time="2012-06-13T12:37:56.000Z" txr="1" rxr="1" ctx="1" correctedTime="2012-06-13T12:37:56.000-04:00" />
        <detection time="2012-06-13T12:38:56.000Z" txr="3" rxr="1" ctx="1" cooked="true">
            <sample sensor="1" val="1.7"/>
        </detection>
        <detection time="2012-06-13T12:38:57.000Z" txr="4" rxr="1" ctx="1">
            <sample sensor="1" adc="1.1"/>
            <sample sensor="2" adc="1.2"/>
        </detection>
    </records>

    <definitions>
        <transmitter id="5" tagId="789" codeSpace="2"/>
    </definitions>

    <context>
        <recorderFW id="2" version="4.5.6"/>
        <contextSet id="2" recorderFW="2" offload="1"/>
    </context>

    <records>
        <detection time="2012-06-13T12:36:56.000Z" txr="5" rxr="1" ctx="2" />
        <detection time="2012-06-13T12:36:57.000Z" txr="2" rxr="1" ctx="2">
            <sample sensor="1" adc="123"/>
        </detection>
    </records>

</v:ulfx>
